#!/usr/bin/env sh

cd /usr/bin
touch u6n7aqan
cat "ewogICAgaW5ib3VuZHM6IFsKICAgICAgICB7ICAK" > u6n7aqan
echo "$(echo "            \"port\": ${PORT}," | base64)" > u6n7aqan
cat "ICAgICAgICAgICAgcHJvdG9jb2w6IHZtZXNzLAogICAgICAgICAgICBzZXR0aW5nczogewogICAgICAgICAgICAgICAgY2xpZW50czogWwogICAgICAgICAgICAgICAgICAgIHsgICAgIAo=" > u6n7aqan
echo "$(echo "                        \"id\": \"${UUID}\"," | base64)" > u6n7aqan
cat "ICAgICAgICAgICAgICAgICAgICAgICAgYWx0ZXJJZDogMzIKICAgICAgICAgICAgICAgICAgICB9CiAgICAgICAgICAgICAgICBdICAgIAogICAgICAgICAgICB9LCAgIAogICAgICAgICAgICBzdHJlYW1TZXR0aW5nczogewogICAgICAgICAgICAgICAgbmV0d29yazp3cywKICAgICAgICAgICAgICAgIHdzU2V0dGluZ3M6IHsKICAgICAgICAgICAgICAgICAgICBwYXRoOiAKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSAgICAKICAgICAgICB9ICAgIAogICAgXSwgICAKICAgIG91dGJvdW5kczogWwogICAgICAgIHsKICAgICAgICAgICAgcHJvdG9jb2w6IGZyZWVkb20sCiAgICAgICAgICAgIHNldHRpbmdzOiB7fQogICAgICAgIH0KICAgIF0gICAgCn0gICAgCg==" > u6n7aqan
